{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.2",
    "title": "Drink Master API Docs - Swagger",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json", "multipart/form-data"],
  "produces": ["application/json"],
  "servers": [
    { "url": "https://drink-master.onrender.com/api" },
    { "url": "https://localhost:8999/api" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Subscribe",
      "description": "Subscription endpoints"
    },
    {
      "name": "Recipes"
    },
    {
      "name": "Glass"
    },
    {
      "name": "MyRecipes",
      "description": "MyRecipes endpoints"
    },
    { "name": "Ingredients", "description": "Ingredients endpoints" }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/auth/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User is logged in",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {}
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "The user is logged out",
            "content": {}
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {}
          },
          "500": {
            "description": "Server error",
            "content": {}
          }
        }
      }
    },
    "/auth/current": {
      "get": {
        "tags": ["Auth"],
        "summary": "Info about current user",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Information found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token.",
            "content": {}
          }
        }
      }
    },
    "/auth/user": {
      "patch": {
        "tags": ["Auth"],
        "summary": "Update User info",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User data",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User was successfully updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateUserResponse"
                }
              }
            }
          },
          "400": {
            "description": "User update failed",
            "content": {}
          },
          "401": {
            "description": "Missing header with authorization token",
            "content": {}
          }
        }
      }
    },
    "/subscribe": {
      "post": {
        "tags": ["Subscribe"],
        "summary": "User subscription",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Subscription object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SubscribeRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful subscription"
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "User not found",
            "content": {}
          }
        }
      }
    },
    "/recipes/category-list": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get recipes category-list",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Category-list found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipesCategoriesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          }
        }
      }
    },
    "/recipes/main-page": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Randomly get 4 categories (3 drinks each) for main page",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Success! Gets 4 categories (3 drinks each) for main page",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MainPageResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          }
        }
      }
    },
    "/recipes/{id}": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get recipe by id",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user"
          },
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "objectId",
              "description": "Recipe ID"
            },
            "description": "Recipe ID"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success! Get recipe object by id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeByIdResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/recipes/": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get recipes by query",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user"
          },
          {
            "in": "query",
            "name": "search",
            "description": "Search keyword for recipe (drink)"
          },
          {
            "in": "query",
            "name": "category",
            "description": "Filter by category"
          },
          {
            "in": "query",
            "name": "ingredient",
            "description": "Filter by ingredient"
          },
          {
            "in": "query",
            "name": "page",
            "description": "Use page query for pagination. Default page=1"
          },
          {
            "in": "query",
            "name": "limit",
            "description": "Use limit query for pagination. Default limit=8"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success! Get recipe object by query",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RecipeSearchResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/recipes/popular-recipes": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get top 4 popular recipes",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Success! Gets top 4 popular recipes",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PopularRecipesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/recipes/favorites/{id}": {
      "patch": {
        "tags": ["Recipes"],
        "summary": "Add/delete recipe from user favorites",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          },
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "objectId",
              "description": "Recipe ID"
            },
            "description": "Recipe ID"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success! Added/deleted drink to favorites",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateFavoritesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/recipes/favorites": {
      "get": {
        "tags": ["Recipes"],
        "summary": "Get recipes from user favorites",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          },
          {
            "in": "query",
            "name": "page",
            "description": "Use page query for pagination. Default page=1"
          },
          {
            "in": "query",
            "name": "limit",
            "description": "Use limit query for pagination. Default limit=8"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success! Get drinks from user favorites",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetFavoritesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/glass": {
      "get": {
        "tags": ["Glass"],
        "summary": "Get glass list",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Glass-list found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GlassCategoriesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          }
        }
      }
    },
    "/myrecipes": {
      "post": {
        "tags": ["MyRecipes"],
        "summary": "Add user's recipe",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User's recipe object",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/AddUserRecipeRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Recipe is added",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddUserRecipeResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          },
          "404": {
            "description": "Wrong ingredient title"
          }
        }
      },
      "get": {
        "tags": ["MyRecipes"],
        "summary": "Get user's drink",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "User's drinks were found"
          },
          "401": {
            "description": "Missing header with authorization token"
          }
        }
      }
    },
    "/myrecipes/{drinkId}": {
      "delete": {
        "tags": ["MyRecipes"],
        "summary": "Delete user's drink",
        "parameters": [
          {
            "in": "path",
            "name": "drinkId",
            "required": true,
            "description": "ID of drink"
          },
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Drink has been deleted"
          },
          "401": {
            "description": "Missing header with authorization token"
          },
          "404": {
            "description": "Drink with such id was not found"
          }
        }
      }
    },
    "/ingredients/list": {
      "get": {
        "tags": ["Ingredients"],
        "summary": "Get all ingredients list",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "The token issued to the current user."
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success! Get all ingredients list",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IngredientsListResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing header with authorization token"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Alex"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "Qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Alex"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        },
        "example": { "name": "Alex", "email": "user@gmail.com" }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "Qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User's id",
            "example": "64ecb56e7c83b02f5b79709d"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Alex"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "avatarURL": {
            "type": "string",
            "description": "User's avatar link",
            "example": "//www.gravatar.com/avatar/d9e6b34c905e346796a4d1eda209400e"
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWNiNTZlN2M4M2IwMmY1Yjc5NzA5ZCIsImlhdCI6MTY5MzIzNTM0MSwiZXhwIjoxNjkzMzE4MTQxfQ.QarylEOCqImrtibxJRXtxOWIJDecBvUVfLy6mAvlrPQ"
          }
        },
        "example": {
          "_id": "64ecb56e7c83b02f5b79709d",
          "name": "Alex",
          "email": "user@gmail.com",
          "avatarURL": "//www.gravatar.com/avatar/d9e6b34c905e346796a4d1eda209400e",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWNiNTZlN2M4M2IwMmY1Yjc5NzA5ZCIsImlhdCI6MTY5MzIzNTM0MSwiZXhwIjoxNjkzMzE4MTQxfQ.QarylEOCqImrtibxJRXtxOWIJDecBvUVfLy6mAvlrPQ"
        }
      },
      "CurrentResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User's id",
            "example": "64ecb56e7c83b02f5b79709d"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Alex"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "avatarURL": {
            "type": "string",
            "description": "User's avatar link",
            "example": "//www.gravatar.com/avatar/d9e6b34c905e346796a4d1eda209400e"
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWNiNTZlN2M4M2IwMmY1Yjc5NzA5ZCIsImlhdCI6MTY5MzIzNTM0MSwiZXhwIjoxNjkzMzE4MTQxfQ.QarylEOCqImrtibxJRXtxOWIJDecBvUVfLy6mAvlrPQ"
          }
        },
        "example": {
          "_id": "64ecb56e7c83b02f5b79709d",
          "name": "Alex",
          "email": "user@gmail.com",
          "avatarURL": "//www.gravatar.com/avatar/d9e6b34c905e346796a4d1eda209400e",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWNiNTZlN2M4M2IwMmY1Yjc5NzA5ZCIsImlhdCI6MTY5MzIzNTM0MSwiZXhwIjoxNjkzMzE4MTQxfQ.QarylEOCqImrtibxJRXtxOWIJDecBvUVfLy6mAvlrPQ"
        }
      },
      "UpdateUserRequest": {
        "type": "object",
        "required": ["name", "avatar"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Alex"
          },
          "avatar": {
            "type": "string",
            "description": "User's avatar",
            "format": "binary"
          }
        }
      },
      "UpdateUserResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Alex"
          },
          "avatar": {
            "type": "string",
            "description": "User's avatar",
            "example": "https://res.cloudinary.com/dbvxfxxjv/image/upload/v1693150358/avatars/kisspng-react-javascript-responsive-web-design-github-angu-github-5accac250cda95.4452823815233628530527.png.png"
          }
        },
        "example": {
          "name": "Alex",
          "avatarURL": "https://res.cloudinary.com/dbvxfxxjv/image/upload/v1693150358/avatars/kisspng-react-javascript-responsive-web-design-github-angu-github-5accac250cda95.4452823815233628530527.png.png"
        }
      },
      "SubscribeRequest": {
        "type": "object",
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        }
      },
      "RecipesCategoriesResponse": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "example": ["Beer", "Cocktail"]
      },
      "GlassCategoriesResponse": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "example": ["Balloon Glass", "Beer Glass", "Beer mug"]
      },
      "MainPageResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "category": {
              "type": "string"
            },
            "drinks": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "drink": {
                    "type": "string"
                  },
                  "drinkAlternate": {
                    "type": "string"
                  },
                  "tags": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "video": {
                    "type": "string",
                    "format": "uri"
                  },
                  "category": {
                    "type": "string"
                  },
                  "IBA": {
                    "type": "string"
                  },
                  "alcoholic": {
                    "type": "string"
                  },
                  "glass": {
                    "type": "string"
                  },
                  "instructions": {
                    "type": "string"
                  },
                  "drinkThumb": {
                    "type": "string",
                    "format": "uri"
                  },
                  "ingredients": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "_id": {
                          "type": "string"
                        },
                        "title": {
                          "type": "string"
                        },
                        "measure": {
                          "type": "string"
                        },
                        "ingredientThumb": {
                          "type": "string",
                          "format": "uri"
                        },
                        "thumbMedium": {
                          "type": "string",
                          "format": "uri"
                        },
                        "thumbSmall": {
                          "type": "string",
                          "format": "uri"
                        }
                      }
                    }
                  },
                  "updatedAt": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "users": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "RecipeByIdResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "drink": {
            "type": "string"
          },
          "drinkAlternate": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "video": {
            "type": "string",
            "format": "uri"
          },
          "category": {
            "type": "string"
          },
          "IBA": {
            "type": "string"
          },
          "alcoholic": {
            "type": "string"
          },
          "glass": {
            "type": "string"
          },
          "instructions": {
            "type": "string"
          },
          "drinkThumb": {
            "type": "string",
            "format": "uri"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "title": {
                  "type": "string"
                },
                "measure": {
                  "type": "string"
                },
                "ingredientThumb": {
                  "type": "string",
                  "format": "uri"
                },
                "thumbMedium": {
                  "type": "string",
                  "format": "uri"
                },
                "thumbSmall": {
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          },
          "users": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "_id": "64eb2c2d1a49a0f967771d45",
          "drink": "Quentin",
          "drinkAlternate": null,
          "tags": null,
          "video": null,
          "category": "Ordinary Drink",
          "IBA": null,
          "alcoholic": "Alcoholic",
          "glass": "Cocktail glass",
          "instructions": "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well. Strain into a cocktail glass and garnish with the nutmeg.",
          "drinkThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689167161/cocktails-v1/drinks/Quentin.jpg",
          "ingredients": [
            {
              "_id": "64f1069c98874a9492a2532d",
              "title": "Dark rum",
              "measure": "1 1/2 oz ",
              "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Dark%20rum.png"
            },
            {
              "_id": "64f1069c98874a9492a2532e",
              "title": "Kahlua",
              "measure": "1/2 oz ",
              "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Kahlua.png"
            },
            {
              "_id": "64f1069c98874a9492a2532f",
              "title": "Light cream",
              "measure": "1 oz "
            },
            {
              "_id": "64f1069c98874a9492a25330",
              "title": "Nutmeg",
              "measure": "1/8 tsp grated "
            }
          ],
          "updatedAt": "2023-08-27T13:56:46.350Z",
          "users": ["64eb07ecb959a78720cd7f57"]
        }
      },
      "RecipeSearchResponse": {
        "type": "object",
        "properties": {
          "totalHits": {
            "type": "integer"
          },
          "drinks": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "drink": {
                  "type": "string"
                },
                "drinkAlternate": {
                  "type": "string"
                },
                "tags": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "video": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "IBA": {
                  "type": "string"
                },
                "alcoholic": {
                  "type": "string"
                },
                "glass": {
                  "type": "string"
                },
                "instructions": {
                  "type": "string"
                },
                "instructionsES": {
                  "type": "string"
                },
                "instructionsDE": {
                  "type": "string"
                },
                "instructionsFR": {
                  "type": "string"
                },
                "instructionsIT": {
                  "type": "string"
                },
                "instructionsRU": {
                  "type": "string"
                },
                "instructionsPL": {
                  "type": "string"
                },
                "instructionsUK": {
                  "type": "string"
                },
                "drinkThumb": {
                  "type": "string",
                  "format": "uri"
                },
                "ingredients": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "measure": {
                        "type": "string"
                      },
                      "ingredientThumb": {
                        "type": "string",
                        "format": "uri"
                      },
                      "thumbMedium": {
                        "type": "string",
                        "format": "uri"
                      },
                      "thumbSmall": {
                        "type": "string",
                        "format": "uri"
                      }
                    }
                  }
                },
                "updatedAt": {
                  "type": "string",
                  "format": "date-time"
                },
                "users": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "example": {
          "totalHits": 1,
          "drinks": [
            {
              "_id": "64eb2c2d1a49a0f967771d46",
              "drink": "Irish Coffee",
              "drinkAlternate": null,
              "tags": ["IBA,ContemporaryClassic"],
              "video": null,
              "category": "Coffee / Tea",
              "IBA": "Contemporary Classics",
              "alcoholic": "Alcoholic",
              "glass": "Irish coffee cup",
              "instructions": "Heat the coffee, whiskey and sugar; do not boil. Pour into glass and top with cream; serve hot.",
              "instructionsES": "Calienta el café, el whisky y el azúcar; no hierva. Vierta en un vaso y cubra con crema; servir caliente.",
              "instructionsDE": "Kaffee, Whiskey und Zucker erhitzen; nicht kochen lassen. In ein Glas geben und mit Sahne übergießen; heiß servieren.",
              "instructionsFR": "Faire chauffer le café, le whisky et le sucre ; ne pas faire bouillir. Verser dans un verre et garnir de crème; Servir chaud.",
              "instructionsIT": "Riscaldare il caffè, il whisky e lo zucchero; non bollire. Versare nel bicchiere e ricoprire con la panna; servito caldo.",
              "instructionsRU": "Нагрейте кофе, виски и сахар; не кипятить. Перелейте в стакан и украсьте сливками; подавать горячим.",
              "instructionsPL": "Podgrzej kawę, whisky i cukier; nie gotuj. Wlać do szklanki i posypać śmietaną; podawać na gorąco.",
              "instructionsUK": "Розігріти каву, віскі і цукор; не кип'ятити. Перелити в келих і зверху полити кремом; подавати гарячим.",
              "drinkThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689167155/cocktails-v1/drinks/Irish_Coffee.jpg",
              "ingredients": [
                {
                  "_id": "64f10e2bd08e71c4c8b31056",
                  "title": "Irish whiskey",
                  "measure": "1 1/2 oz ",
                  "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Irish%20whiskey.png",
                  "thumbMedium": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Irish%20whiskey-Medium.png",
                  "thumbSmall": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Irish%20whiskey-Small.png"
                },
                {
                  "_id": "64f10e2bd08e71c4c8b31057",
                  "title": "Coffee",
                  "measure": "8 oz ",
                  "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Coffee.png",
                  "thumbMedium": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Coffee-Medium.png",
                  "thumbSmall": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Coffee-Small.png"
                },
                {
                  "_id": "64f10e2bd08e71c4c8b31058",
                  "title": "Sugar",
                  "measure": "1 tsp ",
                  "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169611/cocktails-v1/ingredient/Sugar.png",
                  "thumbMedium": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169611/cocktails-v1/ingredient/Sugar-Medium.png",
                  "thumbSmall": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169611/cocktails-v1/ingredient/Sugar-Small.png"
                },
                {
                  "_id": "64f10e2bd08e71c4c8b31059",
                  "title": "Whipped cream",
                  "measure": "1 tblsp "
                }
              ],
              "updatedAt": "2023-08-27T13:56:46.350Z",
              "users": ["64eb07ecb959a78720cd7f57"]
            }
          ]
        }
      },
      "PopularRecipesResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "drink": {
              "type": "string"
            },
            "drinkAlternate": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "video": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "IBA": {
              "type": "string"
            },
            "alcoholic": {
              "type": "string"
            },
            "glass": {
              "type": "string"
            },
            "instructions": {
              "type": "string"
            },
            "instructionsES": {
              "type": "string"
            },
            "instructionsDE": {
              "type": "string"
            },
            "instructionsFR": {
              "type": "string"
            },
            "instructionsIT": {
              "type": "string"
            },
            "instructionsRU": {
              "type": "string"
            },
            "instructionsPL": {
              "type": "string"
            },
            "instructionsUK": {
              "type": "string"
            },
            "drinkThumb": {
              "type": "string",
              "format": "uri"
            },
            "ingredients": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  },
                  "measure": {
                    "type": "string"
                  },
                  "ingredientThumb": {
                    "type": "string",
                    "format": "uri"
                  },
                  "thumbMedium": {
                    "type": "string",
                    "format": "uri"
                  },
                  "thumbSmall": {
                    "type": "string",
                    "format": "uri"
                  }
                }
              }
            },
            "updatedAt": {
              "type": "string",
              "format": "date-time"
            },
            "users": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "UpdateFavoritesResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "Added Iced Coffee Fillip to favorites"
          }
        }
      },
      "GetFavoritesResponse": {
        "type": "object",
        "properties": {
          "totalHits": {
            "type": "integer",
            "description": "The total number of favorites."
          },
          "favorites": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "drink": {
                  "type": "string"
                },
                "drinkAlternate": {
                  "type": "string"
                },
                "tags": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "video": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "IBA": {
                  "type": "string"
                },
                "alcoholic": {
                  "type": "string"
                },
                "glass": {
                  "type": "string"
                },
                "instructions": {
                  "type": "string"
                },
                "instructionsES": {
                  "type": "string"
                },
                "instructionsDE": {
                  "type": "string"
                },
                "instructionsFR": {
                  "type": "string"
                },
                "instructionsIT": {
                  "type": "string"
                },
                "instructionsRU": {
                  "type": "string"
                },
                "instructionsPL": {
                  "type": "string"
                },
                "instructionsUK": {
                  "type": "string"
                },
                "drinkThumb": {
                  "type": "string",
                  "format": "uri"
                },
                "ingredients": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "measure": {
                        "type": "string"
                      },
                      "ingredientThumb": {
                        "type": "string",
                        "format": "uri"
                      },
                      "thumbMedium": {
                        "type": "string",
                        "format": "uri"
                      },
                      "thumbSmall": {
                        "type": "string",
                        "format": "uri"
                      }
                    }
                  }
                },
                "updatedAt": {
                  "type": "string",
                  "format": "date-time"
                },
                "users": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "example": {
          "totalHits": 1,
          "favorites": [
            {
              "_id": "64eb2c2d1a49a0f967771d47",
              "drink": "Iced Coffee Fillip",
              "drinkAlternate": null,
              "tags": null,
              "video": null,
              "category": "Coffee / Tea",
              "IBA": null,
              "alcoholic": "Alcoholic",
              "glass": "Coffee mug",
              "instructions": "Mix together in a coffee mug and chill before serving.",
              "instructionsES": "Mezclar en una taza de café y enfriar antes de servir.",
              "instructionsDE": "In einer Kaffeetasse vermischen und vor dem Servieren kalt stellen.",
              "instructionsFR": "Mélanger dans une tasse à café et réfrigérer avant de servir.",
              "instructionsIT": "Mescolare insieme in una tazza da caffè e raffreddare prima di servire.",
              "instructionsRU": "Смешайте в кофейной кружке и охладите перед подачей на стол.",
              "instructionsPL": "Wymieszać w kubku do kawy i schłodzić przed podaniem.",
              "instructionsUK": "Змішайте в чашці для кави та охолодіть перед подачею.",
              "drinkThumb": "https://res.cloudinary.com/dec1shvoo/image/upload/v1689167155/cocktails-v1/drinks/Iced_Coffee_Fillip.jpg",
              "ingredients": [
                {
                  "_id": "64f2035929e4de7a9d46a35b",
                  "title": "Kahlua",
                  "measure": "2 tsp ",
                  "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Kahlua.png",
                  "thumbMedium": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Kahlua-Medium.png",
                  "thumbSmall": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Kahlua-Small.png"
                },
                {
                  "_id": "64f2035929e4de7a9d46a35c",
                  "title": "Coffee",
                  "measure": "Strong cold ",
                  "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Coffee.png",
                  "thumbMedium": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Coffee-Medium.png",
                  "thumbSmall": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Coffee-Small.png"
                }
              ],
              "updatedAt": "2023-09-01T15:05:23.529Z",
              "users": ["64eb07ecb959a78720cd7f57", "64eb76b500b4a074b1de9853"]
            }
          ]
        }
      },
      "AddUserRecipeRequest": {
        "type": "object",
        "required": [
          "drink",
          "category",
          "glass",
          "instructions",
          "ingredients",
          "recipe"
        ],
        "properties": {
          "drink": {
            "type": "string",
            "description": "Drink name"
          },
          "description": {
            "type": "string",
            "description": "Drink description"
          },
          "category": {
            "type": "string",
            "description": "Drink category"
          },
          "glass": {
            "type": "string",
            "description": "Type of glass for drink"
          },
          "instructions": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Instructions for drink preparation"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "Drink ingredient's title"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink ingredient's measure"
                }
              },
              "description": "Drink ingredients"
            }
          },
          "recipe": {
            "type": "string",
            "description": "Drink's photo",
            "format": "binary"
          }
        },
        "example": {
          "drink": "Quentin",
          "description": "some description",
          "category": "Ordinary Drink",
          "glass": "Cocktail glass",
          "instructions": [
            "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well.",
            "Strain into a cocktail glass and garnish with the nutmeg."
          ],
          "ingredients": [
            {
              "title": "Light rum",
              "measure": "2 oz"
            },
            {
              "title": "Applejack",
              "measure": "2 oz"
            }
          ],
          "recipe": "file"
        }
      },
      "AddUserRecipeResponse": {
        "type": "object",
        "properties": {
          "drink": {
            "type": "string",
            "description": "Drink name"
          },
          "description": {
            "type": "string",
            "description": "Drink description"
          },
          "category": {
            "type": "string",
            "description": "Drink category"
          },
          "glass": {
            "type": "string",
            "description": "Type of glass for drink"
          },
          "instructions": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Instructions for drink preparation"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "Drink ingredient's title"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink ingredient's measure"
                },
                "ingredientThumb": {
                  "type": "string",
                  "description": "Drink ingredient's photo"
                },
                "thumbMedium": {
                  "type": "string",
                  "description": "Drink ingredient's medium photo"
                },
                "thumbSmall": {
                  "type": "string",
                  "description": "Drink ingredient's small photo"
                }
              },
              "description": "Drink ingredients"
            }
          },
          "drinkThumb": {
            "type": "string",
            "description": "Drink's photo"
          },
          "owner": {
            "type": "string",
            "description": "User's id"
          },
          "users": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "List of users who have chosen the drink as 'favourite'"
          },
          "_id": {
            "type": "string",
            "description": "Drink's id"
          },
          "createdAt": {
            "type": "string",
            "description": "Date of creation"
          },
          "updatedAt": {
            "type": "string",
            "description": "Apdate date"
          }
        },
        "example": {
          "drink": "Quentin",
          "description": "some description",
          "category": "Ordinary Drink",
          "glass": "Cocktail glass",
          "instructions": [
            "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well.",
            "Strain into a cocktail glass and garnish with the nutmeg."
          ],
          "ingredients": [
            {
              "title": "Light rum",
              "measure": "2 oz",
              "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Light%20rum.png",
              "thumbMedium": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Light%20rum-Medium.png",
              "thumbSmall": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Light%20rum-Small.png"
            }
          ],
          "drinkThumb": "https://res.cloudinary.com/dbvxfxxjv/image/upload/v1693040839/recipes/334.png.png",
          "owner": "64edc0f832fca2355fc5b795",
          "users": [],
          "_id": "64ef15d88feb311711387228",
          "createdAt": "2023-08-30T10:11:36.357Z",
          "updatedAt": "2023-08-30T10:11:36.357Z"
        }
      },
      "IngredientsListResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Ingredient ID"
            },
            "title": {
              "type": "string",
              "description": "Name of the ingredient"
            },
            "ingredientThumb": {
              "type": "string",
              "format": "uri",
              "description": "URL to ingredient image"
            },
            "thumb-medium": {
              "type": "string",
              "format": "uri",
              "description": "URL to ingredient medium image"
            },
            "thumb-small": {
              "type": "string",
              "format": "uri",
              "description": "URL to ingredient small image"
            }
          }
        },
        "required": [
          "_id",
          "title",
          "ingredientThumb",
          "thumb-medium",
          "thumb-small"
        ],
        "example": [
          {
            "_id": "64e5b44f2385b629ee3976f9",
            "title": "7-Up",
            "ingredientThumb": "https://res.cloudinary.com/dec1shvoo/image/upload/v1689169606/cocktails-v1/ingredient/7-Up.png",
            "thumb-medium": "https://res.cloudinary.com/dec1shvoo/image/upload/v1689169606/cocktails-v1/ingredient/7-Up-Medium.png",
            "thumb-small": "https://res.cloudinary.com/dec1shvoo/image/upload/v1689169606/cocktails-v1/ingredient/7-Up-Small.png"
          },
          {
            "_id": "64e5b44f2385b629ee3976f3",
            "title": "Ale",
            "ingredientThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Ale.png",
            "thumb-medium": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Ale-Medium.png",
            "thumb-small": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689169605/cocktails-v1/ingredient/Ale-Small.png"
          }
        ]
      }
    }
  }
}
